### ISSUE TITLE
REDScript Compilation Error

### ISSUE THREAD

**Issue by dhampirdamsel** [DarkFortuneTeller/DarkFuture#1]
Screenshot pretty much says it all and I've included the log. I'm playing on the Steam 2.13 version without REDMod.

Most recent versions of all dependencies have been installed on clean and freshly verified files. Yours is the only mod I have otherwise.

Thank you for the mod! It looks really cool and I can't wait to play it.

![24_Dec_06_21-46-05](https://github.com/user-attachments/assets/e930feb2-5953-4676-b267-dba31ce1736c)
[redscript_r2024-12-06_21-52-21.log](https://github.com/user-attachments/files/18046012/redscript_r2024-12-06_21-52-21.log)

**Comment by dhampirdamsel** [comment]
So it looks like it was some files I missed. I'm new to modding Cyberpunk and apparently you have to do a whole process to get it working on Linux. Here's the link for anyone else who comes by with a similar issue. Sorry about that! [https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/users-modding-cyberpunk-2077/modding-on-linux](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/users-modding-cyberpunk-2077/modding-on-linux)

**Comment by DarkFortuneTeller** [comment]
I'm glad you found a solution!
